name: Laravel CI EDUC

on:
  push:
    branches: [ educ ]

  pull_request:
    branches: [ educ ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
            php-version: '8.3'
            extensions: mbstring, dom, fileinfo, sqlite3, pdo_sqlite
            coverage: none

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Install NPM dependencies
        run: npm install

      - name: Copy .env
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Build Vite assets
        run: npm run build

      - name: Verify Laravel application
        run: php artisan --version

      - name: Run database migrations
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ":memory:"
        run: php artisan migrate --force
    
        # NOVO: Pokretanje svih Laravel/PHPUnit testova
      - name: Run PHPUnit tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ":memory:"
        run: php artisan test

       # NOVO: Automatski generira oznake builda
      - name: Generate EDUC build information
        if: success()
        run: |
          echo "APP_BUILD=educ-${{ github.run_number }}" >> "$GITHUB_ENV"
          echo "APP_COMMIT=${GITHUB_SHA::7}" >> "$GITHUB_ENV"


      # NOVO: Čita VERSION datoteku iz Git repozitorija
      - name: Read VERSION file
        if: success()
        shell: bash
        run: |

          CURRENT_VERSION=$(cat VERSION)

          echo "Trenutna verzija: $CURRENT_VERSION"

          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV

 # NOVO: Povećava MAJOR, MINOR ili PATCH prema početku commit poruke
      - name: Calculate semantic version
        if: success()
        shell: bash
        run: |
          COMMIT_MESSAGE="${{ github.event.head_commit.message }}"

          echo "Commit poruka: $COMMIT_MESSAGE"
          echo "Postojeća verzija: $CURRENT_VERSION"

          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"

          VERSION_CHANGE="none"
          NEW_VERSION="$CURRENT_VERSION"

          if [[ "$COMMIT_MESSAGE" == breaking:* ]]; then
            MAJOR=$((MAJOR + 1))
            MINOR=0
            PATCH=0
            VERSION_CHANGE="major"
            NEW_VERSION="$MAJOR.$MINOR.$PATCH"

          elif [[ "$COMMIT_MESSAGE" == feat:* ]]; then
            MINOR=$((MINOR + 1))
            PATCH=0
            VERSION_CHANGE="minor"
            NEW_VERSION="$MAJOR.$MINOR.$PATCH"

          elif [[ "$COMMIT_MESSAGE" == fix:* ]]; then
            PATCH=$((PATCH + 1))
            VERSION_CHANGE="patch"
            NEW_VERSION="$MAJOR.$MINOR.$PATCH"

          else
            echo "Commit ne počinje s fix:, feat: ili breaking:."
            echo "APP_VERSION ostaje nepromijenjen."
          fi

          echo "Vrsta promjene: $VERSION_CHANGE"
          echo "Nova verzija: $NEW_VERSION"

          echo "VERSION_CHANGE=$VERSION_CHANGE" >> "$GITHUB_ENV"
          echo "APP_VERSION=$NEW_VERSION" >> "$GITHUB_ENV"



      # NOVO: Instalira Railway CLI
      - name: Install Railway CLI
        if: success()
        run: npm install -g @railway/cli

      # NOVO: Ažurira Railway environment varijable
      - name: Update Railway EDUC build number
        if: success()
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway variable set \
          --service "00_laravel_auth_webshop_ci1" \
          --environment "educ" \
          APP_VERSION="$APP_VERSION" \
          APP_BUILD="$APP_BUILD" \
          APP_COMMIT="$APP_COMMIT"


      - name: EDUC CI uspješan
        if: success()
        run: |
          echo " Promjena verzije: $VERSION_CHANGE"
          echo " Verzija: $APP_VERSION"
          echo "EDUC CI je prošao."
          echo "Build: $APP_BUILD"
          echo "Commit: $APP_COMMIT"

      - name: CI uspješan
        if: success()
        run: |
          echo "================================="
          echo " CI PASSED "
          echo " Projekt je spreman za Railway "
          echo " Datum ";
          echo "================================="

# NOVO U FAZI 6: Izvršava se samo ako je neki prethodni korak pao
      - name: CI nije prošao
        if: failure()
        run: |
          echo "================================="
          echo " CI FAILED "
          echo " Potrebno je provjeriti logove "
          echo " Railway neće deployati ovu verziju "
          echo "================================="

      # NOVO U FAZI 6: Uvijek se izvršava, bez obzira je li CI prošao ili pao
      - name: Završna statistika
        if: always()
        run: |
          echo "===================================="
          echo " Laravel CI završio "
          echo " Repository : ${{ github.repository }}"
          echo " Branch     : ${{ github.ref_name }}"
          echo " Committer  : ${{ github.actor }}"
          echo " Commit SHA : ${{ github.sha }}"
          echo "===================================="


      # NOVO U FAZI 6: Izvršava se samo ako se radi o main grani
      - name: Produkcijska grana
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Ovaj workflow se izvršava na main grani."
          echo "Main grana se u našem primjeru smatra produkcijskom granom."


      - name: Release grana
        if: github.ref == 'refs/heads/release-candidate'
        run: |
          echo "Ovaj workflow se izvršava na release-candidate grani."
          echo "Main grana se u našem primjeru smatra release-candidate granom."          

 # NOVO U FAZI 6: Izvršava se samo ako commit poruka sadrži riječ "deploy"
      - name: Commit sadrži riječ deploy
        if: contains(github.event.head_commit.message, 'deploy')
        run: |
          echo "Commit poruka sadrži riječ deploy."
          echo "Poruka commita: ${{ github.event.head_commit.message }}"
